# Generated by Django 3.2.7 on 2022-03-13 13:26

from django.db import migrations


def copy_src_to_dst(Source, Destination):
    for abc in Source.objects.all():
        dst = Destination(
            title=abc.title,
            start=abc.start,
            description=abc.description,
            slots=abc.slots
        )
        dst.save()
        dst.speakers.set(abc.speakers.all())
        abc.delete()


def forward_course_abc_to_mti(apps, schema_editor):
    """"
    1- para cada ABC, instanciar 1 MTI com todos os atributos
    2- salvar o MTI
    3- associar os speakers do ABC no MTI
    4- deletar o ABC
    # get_model pega o modelo no instante da migração, nao use import model
    """
    copy_src_to_dst(
        apps.get_model('core', 'CourseOld'),
        apps.get_model('core', 'Course')
    )


def backward_course_abc_to_mti(apps, schema_editor):
    copy_src_to_dst(
        apps.get_model('core', 'CourseOld'),
        apps.get_model('core', 'Course')
    )


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0010_course'),
    ]

    operations = [
        migrations.RunPython(forward_course_abc_to_mti, backward_course_abc_to_mti)
    ]
